apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "py-redis.labels" . | nindent 4 }}
    app: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        {{- include "py-redis.selectorLabels" . | nindent 8 }}
        app: {{ .Values.redis.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.redis.image }}"
          imagePullPolicy: {{ .Values.redis.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.redis.port }}
              protocol: TCP
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ .Values.redis.name }}-pvc