apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.python.name }}
  labels:
    {{- include "py-redis.labels" . | nindent 4 }}
    app: {{ .Values.python.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.python.name }}
  template:
    metadata:
      labels:
        {{- include "py-redis.selectorLabels" . | nindent 8 }}
        app: {{ .Values.python.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.python.image }}"
          imagePullPolicy: {{ .Values.python.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.python.port }}
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.name }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"