apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.python.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    {{- include "py-redis.labels" . | nindent 4 }}
    app: {{ .Values.python.name }}
spec:
  rules:
  - host: {{ .Values.dns }}
    http:
      paths:
      - pathType: Prefix
        path: /?(.*)
        backend:
          service:
            name: {{ .Values.python.name }}
            port:
              number: {{ .Values.python.port }}