apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "py-redis.labels" . | nindent 4 }}
    app: {{ .Values.redis.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.redis.name }}
