apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: ds
spec:
  selector:
    matchLabels:
      app: ds
  template:
    metadata:
      name: ds-pod
      labels:
        app: ds
    spec:
      containers:
      - name: myapp-container
        image: nginx
        ports:
          - containerPort: 80