apiVersion: v1
kind: Pod
metadata:
  name: pkad-health
spec:
  containers:
  - name: pkad
    image: poznajkubernetes/pkad:blue
    resources: {}
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 25
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 25
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
