apiVersion: v1
kind: Service
metadata:
  name: helloapp-nbvh-echo-svc
spec:
  selector:
    app: helloapp-nbvh-echo-dep
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-nbvh-echo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp-nbvh-echo-dep
  template:
    metadata:
      labels:
        app: helloapp-nbvh-echo-dep
    spec:
      containers:
      - name: helloapp-nbvh-echo-dep
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080