apiVersion: v1
kind: Service
metadata:
  name: stsf-service
spec:
  clusterIP: None
  selector:
    app: stsf
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stsf
  labels:
    app: stsf
spec:
  serviceName: stsf-service
  replicas: 2
  selector:
    matchLabels:
      app: stsf
  template:
    metadata:
      name: stsf
      labels:
        app: stsf
    spec:
      containers:
      - name: stsf-container
        image: nginx
        ports:
          - containerPort: 80
        env:
          - name: TEST
            value: RETEST
        volumeMounts:
        - name: nginx-local-claim
          mountPath: /usr/local/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-local-claim
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pk-sc
      resources:
        requests:
          storage: 1Gi