apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: my-secrets
  restartPolicy: Never