apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.postgresql.password | b64enc }}
  username: {{ .Values.postgresql.username | b64enc }}